name: nofap
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  confetti: ^0.8.0
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.3.0
  lottie: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/couple.png
    - Assets/coupleenjoy.png
    - Assets/couplesad.png
    - Assets/manalone.png
    - Assets/sit.png
    - Assets/skating.png
    - Assets/smoking.png
    - Assets/task.json
    - Assets/Avatars/avatar1.jpg
    - Assets/Avatars/avatar2.jpg
    - Assets/Avatars/avatar3.jpg
    - Assets/Avatars/avatar4.jpg
    - Assets/Avatars/avatar5.jpg
    - Assets/Avatars/avatar6.jpg
    - Assets/Avatars/avatar7.jpg
    - Assets/Avatars/none.jpg
    - Assets/Frames/frame1.png
    - Assets/Frames/frame2.png
    - Assets/Frames/frame3.png
    - Assets/Frames/frame4.png
    - Assets/Frames/frame5.png
    - Assets/Frames/frame6.png
    - Assets/Lottie/heart.json
    - Assets/Lottie/heartbeat.json
    - Assets/Lottie/done.json
    - Assets/Lottie/streak.json
