// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQ_bx9rMAk7msAzuLcROs-3cdlp_b3bk',
    appId: '1:775453438826:web:54a064c99bf85a2171ab13',
    messagingSenderId: '775453438826',
    projectId: 'nofap-6ea59',
    authDomain: 'nofap-6ea59.firebaseapp.com',
    storageBucket: 'nofap-6ea59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnybAFd2GV7BCXvfvyB2H7RZaYbrfcBsE',
    appId: '1:685393279527:android:4692982e697244fda8ac02',
    messagingSenderId: '685393279527',
    projectId: 'fapfree-d9d86',
    databaseURL: 'https://fapfree-d9d86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fapfree-d9d86.firebasestorage.app',
  );

}